### ISSUE TITLE
Feature-set of modern snippet manager

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#1]
There's only two commits at this point, but it's a great plugin already, and since I've already created a snippet manager for another editor, I'd like to provide a list of features that would be super great to have:
- [x] Embedded functionality to jump between placeholders
with <kbd>Tab</kbd> and <kbd>S-Tab</kbd>, or other user defined mappings.
  - <kbd>Enter</kbd> could be mapped if expansion keys are match snippet
  and completion popup is opened.
- [x] named placeholders,
e.g. `{{TEXT:SELECTION}}`, so selection could contain default text on expand.
- [x] Placeholder order,
e.g. `{{1:TEXT:SELECTION}`, so we could jump in needed order, and skip whole snippet if needed.
- [x] Standard snippet syntax, e.g.
`${1:TEXT}`, `$2`, so other snippets from other managers could be ported and used. This also will make possible to use LSP snippets. [Here's a LSP snippet standard, but it's pretty common for other snippet managers too](https://github.com/Microsoft/language-server-protocol/blob/master/snippetSyntax.md). I've implemented it in my snippet plugin for Vim.
- [x] Mirroring,
e.g. `${1:TEXT}` and `$1` will share same `TEXT` on expansion.
- [x] Distinguish mirrored placeholders from normal placeholders,
so jumping will select needed amount of selections to modify.
- [x] Zero placeholder `${0:TEXT}` or `$0` as last placeholder
and jumpout of snippet boundares would be cool.
- [ ] Visual placeholder `${VISUAL}`
that can yank text and place it to the snippet body.
- [ ] Placeholders with selectable choice variants,
e.g. `${1|hello,world|}`, so on jumping popup menu will allow to select a candidate. I'm not sure if it is possible with Kakoune though.
- [ ] Transformations................ This is tough.

I'll dig into your implementation and see if I can help with implementing those features. I also might extend this list if I remember something that I've didn't mentioned.

**Comment by occivink** [comment]
Thanks for the input. I agree that placeholder support with good features is important. Conceptually I like the idea of using phantom-selection to iterate over them, but it kind of falls short in practice, since you can only iterate one-by-one and there's a good deal of context information that is lost. So I think there is some functionality that should be directly integrated into the extension.
Default text: should be easy
Placeholder order + grouping + iteration: should be ok
Mirroring: should be easy with multiple selections
Standard: unless there is a reason to deviate I guess that's a good syntax
Placeholders with variants: might be doable with `menu`

I didn't get some of the points (visual placeholder and zero placeholder) but it seems like there is enough to do already

**Comment by andreyorst** [comment]
> I didn't get some of the points (visual placeholder and zero placeholder) but it seems like there is enough to do already

Placeholders in stippets are count from first to last, where last. is the largest number or zero, e.g. `$3 $1 $0 $9` we first jump on second placeholder, which is `$1`, then on `$3`, then on `$9` and the last is `$0`.  It is optional placeholder, but this way it makes it easy to make sure that last jump will always stay in the same place no matter how many placeholders you add while editing snippet.

**Comment by andreyorst** [comment]
> (visual placeholder)

This is bit tricky thing. `VISUAL` is a placeholder that is empty by default, but not empty when we yank something with snippet manager. Here's a gif from my Vim snippet plugin:
![demo](https://user-images.githubusercontent.com/19470159/40861835-24aa4a08-65f3-11e8-93ec-0a7367bf5d2a.gif)
Here's what happens here:
I have some variables `int a; int b; int c;`. I select those with Vim visual mode, and press <kbd>Tab</kbd> key. The selection is being cut to special place within my snippet manager. Next time
when I expand any snippet with `${VISUAL}` placeholder in it, this placeholder will be replaced with contents that were cut previously. If we didn't cut anything, this placeholder works like regular empty placeholder `$0`. So `${VISUAL}` is `$0` if no selections were cut.

This is useful when we have bunch of `defines` and we want to wrap those and only those to some preprocessor `if`. You've shown this kind of functionality in the demo when placed include guards, so maybe this isn't necessary.

**Comment by occivink** [comment]
I've pushed a branch with some of these changes, it's not documented yet but some of these features should now be supported: default text, grouping, mirroring and the more standard syntax. For example the for-loop you've mentioned can be implemented as:
```
set window snippets 'for-loop' %{
snippets-insert %{for (int ${1:i}; $1 < $2; $1++) {
    $0
}}}
set window snippets_auto_expand 'fl' 'for-loop'
```
There is also a placeholder highlighter that shows the next placeholders to be selected (using the face `SnippetsNextPlaceholders`) and all the others (using `SnippetsOtherPlaceholders`). It can be added like so
```
addhl global/ ranges snippets_placeholders
```
You can jump to the next placeholders using `snippets-select-next-placeholders`.

**Comment by andreyorst** [comment]
That's just amazing!

# 

On other note, I'd like to discuss current snippet adding mechanism, as I find adding them via modifying option a bit wonky. 

What do you think if snippets were defined in the separate files? I've used this practice, and I found it easier to maintain them this way. Emacs package named yasnippet folows same pattern here. All other snippet managers that I know use single file with lot's of snippet definitions inside.

**Comment by andreyorst** [comment]
It works!
>```
>set window snippets 'for-loop' %{
>snippets-insert %{for (int ${1:i}; $1 < $2; $1++) {
>${indent}$0
>}}}
>set window snippets_auto_expand 'fl' 'for-loop'
>```

However upon jumping to `i` it is selected but not overwritten when I start typing.

Now we need one small thing:
map some key, <kbd>Tab</kbd> for example, to call `snippets-select-next-placeholders` while we inside snippet. This is tricky part really. I did it this way in my snippet manager, but it wasn't really reliable:
1. On expand remember snippet starting line and amount of lines
2. Tab key pressed. Check if we inside snippet range of lines
  - `true` - jump to next
  - `false` - act as tab key acts accordingly to user configurations
3. Check if snippet grew since last jump, and go to `1.`

Also it would be nice to have backward jumping too, since user may mess up some placeholder.

**Comment by occivink** [comment]
>However upon jumping to i it is selected but not overwritten when I start typing.

Ah I didn't realize that was expected. I suppose it's in line with how other editors work with selections, but it might be difficult to do properly here. Maybe with an InsertKey hook, but I'm not convinced we should do this. 

>to call snippets-select-next-placeholders while we inside snippet

What do you think of unmapping as soon as the last placeholder is reached? That would be easy to implement.

>Also it would be nice to have backward jumping too, since user may mess up some placeholder.

Yeah I think I need to change that, currently I completely discard the previous placeholders but it would be easy to keep them and expose another command.

>What do you think if snippets were defined in the separate files?

Do you have some documentation of how that works in other plugins? Exposing an option is more kakoune-esque so I tend to prefer it, but maybe we could expose some higher-level feature that sets hooks and options depending on the snippets directory structure.

**Comment by andreyorst** [comment]
Also, when I've did my snippet manager for Vim, I've implemented a mechanism for Tab key. It checked previously entered text and if it is a trigger for snippet, it expanded it. Otherwise it worked as normal Tab key. Any plans on this one?

**Comment by andreyorst** [comment]
> Ah I didn't realize that was expected. I suppose it's in line with how other editors work with selections, but it might be difficult to do properly here. Maybe with an InsertKey hook, but I'm not convinced we should do this.

One way to handle this is to switch to normal mode after every jump, allowing user to press <kbd>c</kbd>, <kbd>a</kbd>, or any other key. This will go along with Kakoune philosophy, but will be very, very annoying. As annoying as current way that we start in insert mode and text is inserted inside multiple character selection.

The other way is to create commands for appending inside insert mode, and clear selection if arbitrary key were pressed. For example:

Define <kbd>Alt+a</kbd> to `snippets-append`. So after jump the only thing we need to check is this:
<kbd>Alt-a</kbd> ? `snippets-append` : `snippets-discard-default-text`

**Comment by occivink** [comment]
Would you mind creating separate issues for the different topics, so that they can be tracked and the discussion can be more focused?

**Comment by occivink** [comment]
Thanks a lot. Yeah I think it's served its purpose
