### ISSUE TITLE
Plugin should do nothing if Perl not installed

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#15]
Currently if perl isn't installed, plugin works only in half way: snippet is inserted, but indentation and cursors are not. This may look misguiding for new users, because they may miss that Perl is required. It would be better if plugin tested `command -v perl` and throwed an error and info message about it's requirements.

**Comment by occivink** [comment]
I'll do it because it's good practice, but how many systems don't have perl installed one way or another? Considering it's a dependency of git and many other tools.
Do you have such a system?

**Comment by andreyorst** [comment]
my phone did not had it installed in termux.
