### ISSUE TITLE
Can't expand rust closure snippet

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#18]
I've *ported* my *[snippet collection]()* to work with your plugin, and now I'm testing it.

I can't expand `||` snippet, which is defined like so:
filename: `|| - Closure, anonymous function (inline)`
```
${1:move} |${2:entry}| { ${0:/* body */} }
```

**Comment by occivink** [comment]
Same here, try renaming the file `\|\| - Closure, anonymous function (inline)`
