### ISSUE TITLE
Using |} in snippet trigger seems to break loading

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#19]
Another snippet for Rust.

filename: `|} - Closure, anonymous function (block)`
```
${1:move }|${2:what}| {
        ${0:/* body */}
}
```

Trying to load this snippet produces this error message:
```
error running hook WinSetOption(snippets='Closure, anonymous function (block)' '|}' 'snippets-insert ''${1:move }|${2:what}| {
	${0:/* body */}
}'' ')/: 2:6: 'set' regex parse error: unexpected '}' at '(|<<<HERE>>>})'
```

**Comment by occivink** [comment]
I hazard a guess that it's because of the trigger, if you want to use regex meta characters you have to escape them, so you'd have to rename the file `\|\} - Closure, anonymouse function (block)`

**Comment by andreyorst** [comment]
Yeah. you right.
