### ISSUE TITLE
LSP completion snippets

### ISSUE THREAD

**Issue by vbauerster** [occivink/kakoune-snippets#22]
I use [bingo](https://github.com/saibing/bingo) lsp server with [kak-lsp](https://github.com/ul/kak-lsp). Completion has some snippet like placeholder. I installed this plugin with hope, that I'll be able to jump to that placeholders, but nothing happens out of the box.
[![Screenshot-2019-02-15-at-16-22-02.png](https://i.postimg.cc/XJxtXMsr/Screenshot-2019-02-15-at-16-22-02.png)](https://postimg.cc/bDDmF5cP)

Is it possible to jump to placeholders in such completion snippets? If yes how do I config?

**Comment by occivink** [comment]
You're right that it is currently unsupported, at the moment a kakoune completion is just a bunch of text that gets inserted before the cursor so it would be difficult to implement this. 
However, there is a kakoune issue (and a branch) about making completions more flexible (https://github.com/mawww/kakoune/issues/2347) so it might already be possible there. I'm not very familiar with how completions work in kakoune so I'd have to investigate that.

**Comment by occivink** [comment]
Snippets are now supported directly in kak-lsp
