### ISSUE TITLE
Snippet load error

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#24]
during testing #23 Ive encountered problem with loading `jdj'\;;l - -=[]\,.kdj`. I don't think that anyone would use such thing, but obviously there shouldn't be any error since all characters are valid.

```
error running hook WinSetOption(snippets='-=[]\,.kdj' 'jdj''\;;l' 'snippets-insert ''vaiv'' ')/: 2:6: 'set' regex parse error: unknown atom escape ';' at '(jdj'\;<<<HERE>>>;l)'
```

**Comment by occivink** [comment]
That's because the regex syntax only allows known escapes, and will complain otherwise. If you search for `\;` you'll see the same thing happening.

**Comment by andreyorst** [comment]
got it
