### ISSUE TITLE
Show snippet expansion token, instead of snippet name

### ISSUE THREAD

**Issue by vbauerster** [occivink/kakoune-snippets#25]
At the moment commands `snippets` and `snippets-menu` list snippet names.
Usually when I type, I need to know what expansion token is, not what snippet name is. It is not very convenient, because there is no way to see expansion tokens available, without context switching.
In my opinion at least `snippets-menu` should list snippet expansion tokens.

**Comment by occivink** [comment]
What is the problem here, that you're not aware of which snippets are available? If that's the case I would think `snippets-info` is what you're looking for, not `snippets-menu`

**Comment by vbauerster** [comment]
Yes you are right. Somehow I missed `snippets-info`, this is what I need.
