### ISSUE TITLE
The plugin doesn't work in kak headless session mode

### ISSUE THREAD

**Issue by vbauerster** [occivink/kakoune-snippets#27]
If I run kak in a headless session mode like `kak -d -s mysession`, then connect to that session with `kak -c mysession`, none of the plugin related commands work, same with snippet expansion in insert mode - it doesn't work.

**Comment by occivink** [comment]
Mh that's interesting, but it looks like the only issue is that `snippet-directory-reload` is not being run; if you run it manually after connecting the plugin should work normally.
More specifically, it looks like no `KakBegin` hook is being run when starting a session via `kak -d -s ..`.

**Comment by occivink** [comment]
Wait that's not correct, they do get run
