### ISSUE TITLE
:snippets-info does not work for rust filetype

### ISSUE THREAD

**Issue by vbauerster** [occivink/kakoune-snippets#29]
I've accompanion [kakoune-snippet-collection](https://github.com/andreyorst/kakoune-snippet-collection) plugin installed and have following setting in my setup:
```
set-option -add global snippets_directories "%opt{plug_install_dir}/kakoune-snippet-collection/snippets"
```
However invoking `:snippets-info` command in rust files shows nothing, I mean there is no pop up at all. This is strange as it works in go files for example. I tested in macos and arch linux and it is same behaviour.

**Comment by occivink** [comment]
I had not commented on this, but I think the issue stemmed from a configuration issue. In any case the `snippets_directories` concept has now been removed so I believe this does not apply anymore.
Just comment again if this is somehow still relevant.
