### ISSUE TITLE
`(` in snippet file name cause error

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#36]
If I add this snippet for `kak` filetype:
```bash
touch "^hello - (descr)"
echo snippet > \^hello\ -\ \(descr\) 
kak test.kak
```

In `*debug*` I see:
```
shell stderr: <<<
sh: 1: eval: Syntax error: "(" unexpected
```

Snippets itself seem to work fine. This is on `auto-discard` branch.

**Comment by codesoap** [comment]
I think this might be solved in https://github.com/occivink/kakoune-snippets/pull/35. Be wary that https://github.com/occivink/kakoune-snippets/pull/37 is still open.
