### ISSUE TITLE
What is the state of the project ?

### ISSUE THREAD

**Issue by sucrecacao** [occivink/kakoune-snippets#41]
Is it working ?  abandoned ?

**Comment by occivink** [comment]
"Abandoned" is probably the right word. I haven't spent the time integrating it into my workflow so the usual incentive I have for working on plugins is not there. 
In addition, I'm not too happy with the complexity of the plugin (it's easily the most complex I've made), and I would like to reduce its scope to make it more manageable. 
As for whether it is working, as far as I know it does.

**Comment by occivink** [comment]
I've started a tentative revival of this plugin, with reduced scope. We'll see if I can commit to it this time.
