### ISSUE TITLE
[Feature Request] Discard default text if nothing is changed

### ISSUE THREAD

**Issue by ellistg** [occivink/kakoune-snippets#43]
The use case for this would be as follows: 
```latex
\usepackage[possibly something]{definitely something}
```
could there be an option so that the default text of `[]` would be deleted if you just jumped to the next snippet?

Hope this makes sense and thanks for the great plugin!

**Comment by occivink** [comment]
Considering the recent scope reduction, I'm going to consider such a feature as out-of-scope as well.
