### ISSUE TITLE
Expansions inside snippets

### ISSUE THREAD

**Issue by eko234** [occivink/kakoune-snippets#45]
Hi, I'm trying to define some global scope snippets, I've been able to do so with a '(.*)' directory, but I also want to be able to declare
expansions in snippet and run it in the context I'm in, for example I often use this convention when commenting code to have
context about when that happened, and I would like to have it for any file type, and being able to eval those expressions easily, 
`%opt{comment_line} NOTE %sh{date}`, I clearly could do this with a user define command and mapping, but the idea to use snippets
for other purposes more than code itself would be an interesting idea, and the framework this plugin provides could be used to provide such feature, I would like to know what you think about.

thanks for you work!

**Comment by occivink** [comment]
Sounds like a nice idea. I think it would be possible by replacing [this line](https://github.com/occivink/kakoune-snippets/blob/master/snippets.kak#L219) by `eval reg dquote '%arg{1}'`, which would 'force' another level of expansion. Of course that would mean quoting the arg, and having to escape the snippet syntax AND the kakoune syntax on top, which might be cumbersome when defining the snippets.
So all in all feasible but not trivial. Though I probably won't work on it, as I've stopped using this plugin in its current state.

**Comment by eko234** [comment]
Oh, I understand, I'm taking a look at the code and seeing if I take the step to hack something together as indeed the nesting of
expansion make it complex to delegate the task as it would be better done by kakoune, may I ask what are you using in this plugin stead?

**Comment by occivink** [comment]
My dark secret is that I've never actually used this plugin (in a real context), I made it to scratch an itch but then never integrated it into my workflow. 
At the same time I don't really like the current design of some parts of this plugin, it's somewhat 'maximalist' and tries to do everything. I've made a [branch](https://github.com/occivink/kakoune-snippets/tree/stripped-v2) where I stripped down the plugin to a state I like better, but there again I haven't taken the time to integrate it into my workflow. So I've not pulled the trigger of merging. 
I guess I just don't need snippets that badly (or maybe I just don't know what I'm missing out on).

**Comment by eko234** [comment]
hahahah very interseting situation of yours, well, I do not use the snippet functionality per se either, but I stole some commands of the plugin to make it easier to define other commands that just put a predefined text where I want, like creating templates for certain kind of files. Well I guess maybe I can stick to user defined commands, I'll check out that branch and maybe someday I will upload my take on the subject, thanks once again :).
