### ISSUE TITLE
Snippets broken on kakoune 2022.10.31

### ISSUE THREAD

**Issue by roket1428** [occivink/kakoune-snippets#48]
After upgrading to the latest version, kakoune always expand first snippet in the snippets directory

snippet dir:
https://ttm.sh/0TI.png

example:
https://asciinema.org/a/WwCNDqnluiqv72DJkGq4lmDDu

workaround:
reverting to 2021.11.08 fixes this issue

edit: didn't see #46 sorry

**Comment by occivink** [comment]
If you can confirm that #47 fixes it I'll merge it

**Comment by roket1428** [comment]
yes, it did fix the problem
