### ISSUE TITLE
[Feature Request] Allow loading snippets from separate files

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#6]
This will allow to create snippet packs for users who don't want to define their own snippets, and will hugely help organize snippets for different languages.

The stcucture should look like that:
```
snippets # multiple files per fyletype directory
    Cpp
        for.snip
        if.snip
    Java
        for.snip
        if.snip

snippets single file for single filetype
    cpp.snippets
    java.snippets
```
Of course those fies can be an arbitrary kakoune scripts, but it would be more common to define a filetype for snippet files, add a syntax highlighting.

Snippets can be one snippet per file located in fyletype folder, like in yasnippet, or one file per filetype with all snippets for current language as shown in the example above.

- The first method involves getting a trigger and finding a file with the name same as trigger. That's yasnippet and simplesnippets.vim approach
- The second method involves parsing a snippet file, to find a trigger inside it, and extract snippet from it. That's Ultisnips and Vscode approach

**Comment by andreyorst** [comment]
I think that json will be nice to use, since Kakoune already has integrations with Jq, and Visual Studio Code uses json for snippets just fine. It also will make parsing easier.

**Comment by occivink** [comment]
Since loading options from a file is not very kakounesque but I can see that it has merits, I'm thinking of adding a separate (optional) file `snippets-directory.kak` that would read the snippets like that:
```
kak
├── snippets
│   ├── cpp
│   │   ├── elif - if { } else { }
│   │   ├── for - For loop
│   │   └── if - if { }
│   └── kak
│       ├── decl - Option declaration
│       ├── def - Command definition
│       └── try - try %{ } catch %{ }
├── snippets-directory.kak
└── snippets.kak
```
With the convention that that anything before ` - ` in the filename is the trigger, and everything after is the snippet name. The directory names in `snippets` refer to the filetypes to which they apply.
The contents of the file would simply be the argument to `snippet-insert`

**Comment by andreyorst** [comment]
looks fine to me. I've stored descriptions is separate file, but this seems more reliable way to do it.

**Comment by andreyorst** [comment]
I think that you don't even need the `-`, since triggers can't contain space inside them, so the first space will be marker. `-` only makes it prettier

**Comment by andreyorst** [comment]
After #16, we can use `^` in trigger name, to make it expandable only if it is in the beginning of the line, as well as other regex marks like `\b`, which means if snippet will be defined as you've proposed above, filenames will contain those regexes:
```
c
├── \bif - if { }
└── ^#if - #if #endif
```
Which may be difficult later to parse as those will need to be escaped when we need to access file contents on expansion of the snippet. Your thoughts?

**Comment by occivink** [comment]
I'm not sure if this is going to be much of a problem, on Linux at least you can use pretty much anything as part of a filename, with the notable exception of `/`. Using ` - ` as a separator is probably also fine since I can't imagine somebody using this as a trigger. 
I'm not convinced that this is a strong enough reason to move to a structured file format which would be more complex to parse, but also for the user imo.
As for escaping, we're dealing arbitrary input so we need to be careful but we have the tools to deal with it.

**Comment by occivink** [comment]
Right, it's a sensible feature, it had just slipped my mind. I just added it.
There is currently an issue where snippets are added twice (caused by https://github.com/mawww/kakoune/issues/2397), I'm considering my options to work around it.

**Comment by occivink** [comment]
I can't think of a clean way to handle that, I guess it's fine to keep it that way until the issue is fixed, since it will only affect `snippets-info`.

**Comment by occivink** [comment]
I haven't tested, but I think you might be able to create a `(c|cpp)` directory and the snippets should be loaded in either cases

**Comment by occivink** [comment]
Also I think at the moment we don't handle properly changes from one filetype to another in a given buffer

**Comment by occivink** [comment]
Ok it needed a couple of fixes, but the `(cpp|kak)` syntax should now work, I find it pretty elegant.

**Comment by andreyorst** [comment]
IIUUC `(c|cpp)` will allow loading `C` snippets in `Cpp` buffers which is Ok, but it will also load `Cpp` snippets in `C` buffer, which isn't Ok, snice those snippets make no sense in `C`?

**Comment by occivink** [comment]
Well yeah, you would put the shared snippets in `(c|cpp)/` and the language specific ones in `c/` and `cpp/`

**Comment by andreyorst** [comment]
Ah, so I could have both `c`, `cpp` and `(c|cpp)` folders. That wasn't clear.

Also I'm experiencing troubles. Empty snippets are being inserted when inserted from files.

**Comment by occivink** [comment]
My bad, testing code that was supposed to be temporary

**Comment by andreyorst** [comment]
Also, It would be cool to have `all` folder for snippets that are loaded for every filetype.

**Comment by occivink** [comment]
You can use `\w*` or `.*` as I've mentioned in the README

**Comment by andreyorst** [comment]
what do you think about creating a repository to store public collection ofsnippets? Other people, who use your plugin could contribute into it, and it would be a centralized place to come and get most common snippets for various languages. I can port snippets from other repos, like Ive did with my snippets for simplesnippets.vim, as well as from UltiSnips/SnipMate repo.

Being a separate repo will not force anyone to use them if they want only their own, but I think most of people would like it, as it is a complete experience basically.

**Comment by occivink** [comment]
If you feel like starting such a repo be my guest, I won't necessarily contribute but I can officially endorse it

**Comment by andreyorst** [comment]
What name should it take? `kakoune-snippets` would be appropriate one, because it means snippets for kakoune, and will follow the same pattern as other editors ([vim-snippets](https://github.com/honza/vim-snippets), [emacs-snippets](https://github.com/hlissner/emacs-snippets) [vscode-.*?-snippets](https://github.com/search?q=vscode-snippets)) but it will be confusing, because this plugin already uses this name.

**Comment by occivink** [comment]
What about `kakoune-snippets-collection`? But I agree that we should avoid name collisions, if only to make it simpler to clone the repo.

**Comment by andreyorst** [comment]
The problem is, that the `kakoune-snippets` is a name that's more representing of the collection of snippets for Kakoune, than a plugin. Since you name all your plugins with the pattern `kakoune-.*` I wouldn't ask to rename this plugin (also because it is too much to ask, I think) but i don't like the `collection` in the same way I wouldn't like to see your plugin called `kakoune-snippet-manager`. It is bit too long name for my taste.

`kak-snippets` could work, but it will be confused with `kakoune-snippets`
`snippets-for-kakoune` is shorter than `kakoune-snippets-collection` but it may misguide users, since it says that snippets are for *Kakoune*, and not for `kakoune-snippets`

If I don't come up with anything I'll probably use `kakoune-snippets-collection`

**Comment by andreyorst** [comment]
@occivink I've made the repo: [kakoune-snippet-collection](https://github.com/andreyorst/kakoune-snippet-collection)
