### ISSUE TITLE
[Feature Request] Expand snippet on special keypress

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-snippets#9]
It would be handy to have an option to expand snippets when some user-definde key is pressed. Automatic expansion is good feature, but not always wanted.
I like to expand snippets with <kbd>Tab</kbd>, and jump betwen placeholders with <kbd>Tab</kbd> too. This involves some problems when you actually want to insert tab character. When I've designed SimpleSnippets.vim, I've implemented a function, that checked if typed text is a trigger, and if it is it inserted a snippet, otherwise it acted as tab key was pressed. That allowed me to use tab to completions and snippets.

**Comment by occivink** [comment]
I made some changes to allow this, you should now be able to do something like:
```
try %{
   snippets-expand-trigger
} catch %{
    exec <tab>
}
```
Note that the commit also comes with some breaking changes in the option names.

**Comment by andreyorst** [comment]
I can't get it to work. I've defined a snippet like this:
```kak
set global snippets 'for' %{
snippets-insert %{for (int ${1:i}; $1 < $2; $1++) {
${indent}$0
}}}
```

After that I've tried to:
```kak
    hook global InsertKey <ret> %{ try %{ snippets-expand-trigger } }
```
and every time I type `for` I get `not a valid trigger` error

**Comment by occivink** [comment]
Right some of this stuff is still a bit underdocumented. I still rely on the two options for (maybe it's worth merging all this stuff into one at some point) for defining the snippet and its trigger, so currently you would have to do something like that
```
set global snippets_auto_expand false
set global snippets 'For loop' %{
snippets-insert %{for (int ${1:i}; $1 < $2; $1++) {
${indent}$0
}}}
set global snippets_triggers 'for' 'For loop'
```
And for using `<ret>`, I'd suggest using a mapping instead of a hook, so that we don't have to remove the inserted newline:
```
def snippet-or-newline %{ try %{ snippets-expand-trigger b } catch %{ exec <ret> } }
map global insert <ret> "<a-;>: snippet-or-newline<ret>"
```
... I guess there is still a way to go before this can be considered user-friendly

**Comment by andreyorst** [comment]
> maybe it's worth merging all this stuff into one at some point

Consider implementing this as part of #6. I think it would be much better to have triggers defined within snippet syntax, and not Kakoune configuration.

For example, yasnippet snippet definition:
```yasnippet
# -*- mode: C -*-
# name: for
# key: for
# --
for (${1:int} ${2:i} = 0; $2 ${3:< 10}; $2${4:++}) {
    $0
}
```
`key` is the thigger here, and snippet body is defined after the header.

Here's how it is done in UltiSnips:
```
snippet for "for loop (for)"
for (${2:i} = 0; $2 < ${1:count}; ${3:++$2}) {
	${VISUAL}$0
}
endsnippet
```

# 

Yeah, your example works just fine. I think such command should be part of snippet, so user just could map it on some key, without explicitly defining it.

**Comment by andreyorst** [comment]
By the way. Do you somehow track that we are currently within active snippet? If yes, 

```kak
define-command snippets-expand-or-jump %{
    try %{
        snippets-expand-trigger b
    } catch %{
        snippets-jump-forward-or-key
    }
}

define-command snippets-jump-forward-or-key %{
    try %{
        snippets-jump-forward
    catch %{
        execute-keys some_user_set_key
    }
}

map global insert some_user_set_key "<a-;>: snippet-expand-or-jump<ret>"
```

This way we could use the same key for both expanding and jumping.

**Comment by occivink** [comment]
>Do you somehow track that we are currently within active snippet?

Not in the sense of the cursor position, but a cheap workaround to that is to keep track of whether there are placeholders remaining. So:

```
define-command snippets-expand-or-jump %{
    try %{
        snippets-expand-trigger b
    } catch %{
        snippets-jump-forward
    } catch %{
        exec <key>
    }   
}
```

**Comment by andreyorst** [comment]
It would be cool to have such function inside plugin core, except it should be ready to use user's keys. Something like so:

```kak
declare-option str snippets-user-mapping "<tab>"

map %opt{snippets-user-mapping} <a-;>:<space>snippets-expand-or-jump<ret>

define-command snippets-expand-or-jump %{
    try %{
        snippets-expand-trigger b
    } catch %{
        snippets-jump-forward
    } catch %{
        exec %opt{snippets-user-mapping}
    }   
}
```

Except I'm not sure if this `map` will respect user config at all...

**Comment by andreyorst** [comment]
With such config:
```kak
map global insert '<tab>' "<a-;>: snippets-expand-or-jump 'tab'<ret>"

hook global InsertCompletionShow .* %{
    try %{
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert '<ret>' "<a-;>: snippets-expand-or-jump 'ret'<ret>"
    }
}

hook global InsertCompletionHide .* %{
    unmap window insert '<ret>' "<a-;>: snippets-expand-or-jump 'ret'<ret>"
}

define-command snippets-expand-or-jump -params 1 %{
    try %{
        snippets-expand-trigger b
    } catch %{
        snippets-select-next-placeholders
    } catch %sh{
        case $1 in
            ret|tab)
                printf "%s\n" "execute-keys <$1>" ;;
            *)
                printf "%s\n" "execute-keys $1" ;;
        esac
    }
}}
```
It works like so:

![vaiv](https://user-images.githubusercontent.com/19470159/51431625-c3329b80-1c3c-11e9-8323-c9d9aa87c913.gif)

And that's just amazing.

**Comment by occivink** [comment]
I don't really want to start wiki pages yet, but feel free to them if you wish, I'll update them in case of breaking changes.
